// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: pokemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pokenmon int32

const (
	Pokenmon_SmallFoxDog Pokenmon = 0 // 小小狐狸犬
	Pokenmon_WaterDog    Pokenmon = 1 //水🐕
	Pokenmon_GrassTurtle Pokenmon = 2 //草龟
	Pokenmon_FireCat     Pokenmon = 3 //火猫
)

// Enum value maps for Pokenmon.
var (
	Pokenmon_name = map[int32]string{
		0: "SmallFoxDog",
		1: "WaterDog",
		2: "GrassTurtle",
		3: "FireCat",
	}
	Pokenmon_value = map[string]int32{
		"SmallFoxDog": 0,
		"WaterDog":    1,
		"GrassTurtle": 2,
		"FireCat":     3,
	}
)

func (x Pokenmon) Enum() *Pokenmon {
	p := new(Pokenmon)
	*p = x
	return p
}

func (x Pokenmon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pokenmon) Descriptor() protoreflect.EnumDescriptor {
	return file_pokemon_proto_enumTypes[0].Descriptor()
}

func (Pokenmon) Type() protoreflect.EnumType {
	return &file_pokemon_proto_enumTypes[0]
}

func (x Pokenmon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pokenmon.Descriptor instead.
func (Pokenmon) EnumDescriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{0}
}

var File_pokemon_proto protoreflect.FileDescriptor

var file_pokemon_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2a, 0x47, 0x0a, 0x08, 0x50, 0x6f, 0x6b, 0x65,
	0x6e, 0x6d, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x46, 0x6f, 0x78,
	0x44, 0x6f, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x61, 0x74, 0x65, 0x72, 0x44, 0x6f,
	0x67, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x73, 0x73, 0x54, 0x75, 0x72, 0x74,
	0x6c, 0x65, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x69, 0x72, 0x65, 0x43, 0x61, 0x74, 0x10,
	0x03, 0x42, 0x10, 0x5a, 0x0e, 0x50, 0x6f, 0x6b, 0x65, 0x6e, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pokemon_proto_rawDescOnce sync.Once
	file_pokemon_proto_rawDescData = file_pokemon_proto_rawDesc
)

func file_pokemon_proto_rawDescGZIP() []byte {
	file_pokemon_proto_rawDescOnce.Do(func() {
		file_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_pokemon_proto_rawDescData)
	})
	return file_pokemon_proto_rawDescData
}

var file_pokemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pokemon_proto_goTypes = []interface{}{
	(Pokenmon)(0), // 0: pokemon.Pokenmon
}
var file_pokemon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pokemon_proto_init() }
func file_pokemon_proto_init() {
	if File_pokemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pokemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_proto_goTypes,
		DependencyIndexes: file_pokemon_proto_depIdxs,
		EnumInfos:         file_pokemon_proto_enumTypes,
	}.Build()
	File_pokemon_proto = out.File
	file_pokemon_proto_rawDesc = nil
	file_pokemon_proto_goTypes = nil
	file_pokemon_proto_depIdxs = nil
}
